export const AUTHACTIONS = {
  SET_LOADING: "SET_LOADING",
  SET_USER: "SET_USER",
  SET_ERROR: "SET_ERROR",
  SET_USERS: "SET_USERS",
  SET_LOGIN: "SET_LOGIN",
  SET_SIGN_UP: "SET_SIGN_UP",
  SET_FORGOT_PASSWORD: "SET_FORGOT_PASSWORD",
  SET_LOGOUT: "SET_LOGOUT",
};
